name: .NET test

on:
  pull_request:
    branches: [ "develop" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --logger "trx;LogFileName=test-results.trx" || true --verbosity normal
    - name: roslynator
      run: dotnet tool install -g roslynator.dotnet.cli
    - name: roslynator test
      run: roslynator analyze
    - name: Test Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: Upload .NET Test results
        path: "**/test-results.trx"                            
#        reporter: dotnet-trx
#        fail-on-error: true